spring.application.name=ms-digitalfix-workorders

spring.datasource.url=jdbc:oracle:thin:@digitalix_low?TNS_ADMIN=${DB_WALLET_PATH}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update